### PR TITLE
items are listed alphabetically and case insensitive

### LINKED ISSUE #44: Alphabetize list items in List.jsx
Currently the shopping list items in `List.jsx` are sorted based on the 'groups' configuration array and the items display in their respective groups for how soon the item will need to be purchased again. However, the items do not display alphabetically within each of those groups. 

Previously I was attempting to alphabetize using the `.sort()` method but was unsuccessful. Another route we can look at is using Firebase's built in `orderBy()` method:

[Order and limit data with Cloud Firestore](https://firebase.google.com/docs/firestore/query-data/order-limit-data)

### PR DESCRIPTION
**Pull request by Trevor-Rezac**
## Description

This PR adds a new feature which improves the UI/UX. The items on the user's shopping list are now alphabetized within their corresponding groups. The alphabetization is case insensitive which allows the user to quickly identify their items regardless of how the item was initially typed. 

## Related Issue

Closes #44 

## Acceptance Criteria

- [x] Items display alphabetically within their corresponding purchase timeframe groups. 
- [x] Alphabetization is case insensitive

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

### Before

Screen Shot 2022-08-23 at 8 44 08 AM

### After

Screen Shot 2022-08-23 at 8 46 29 AM

## Testing Steps / QA Criteria
1. From your local machine `git checkout main` then `git pull`
2. `git checkout TR-alphabetize-list`. 
3. `npm run start`
4. If you do not already have a list, create one then begin adding items. 
    - Add items starting with same letter as well as both lowercase and uppercase
    - Add items within each category of how 'soon' you will need to buy the item

### CODE REVIEW

**Review by N-Zubko — APPROVED** [review]
I checked as per the instruction, everything is working and items are alphabetized. Great job, @Trevor-Rezac !

**Review by michellerenehey — APPROVED** [review]
Looks great, @Trevor-Rezac revor! Nice job!

**Review by mira-kine — APPROVED** [review]
awesome work pushing through and also figuring out ordering serverside! It feels cleaner and more bug proof. Looks good to me!

**Review by lindseyindev — APPROVED** [review]
Works and looks great! Firebase isn't case insensitive and I was [reading this stackoverflow issue ](https://stackoverflow.com/questions/48096063/cloud-firestore-case-insensitive-sorting-using-query) that talks about the complexity in normalizing unicode values and they begin with very similar logic and data structure you implemented here to be able to order case insensitve. 

I was also reading about the [.normalize() method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize) in javascript and it is beyond the scope of this issue but I found it really interesting and I just want to share it as something that exists!

**Pull request merged**
