### PR TITLE
Hotfix! Remove extra logOut button

### LINKED ISSUE #64: Hotfix! logOut button breaking the app
A quick fix to get Shop-Ade working again!

### PR DESCRIPTION
**Pull request by michellerenehey**
## Description

Oopsies our app was breaking! Looks like an extra logOut button didn't get deleted at some point in our merges. 

## Related Issue
Closes #64. 

## Acceptance Criteria
- [X] Remove extra logOut button in `<List/>` component to get avoid reference error from breaking the app. 

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|  ✓   | :bug: Bug fix              |
|    | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

## Testing Steps / QA Criteria
1. `git checkout main`
2. `git pull`
3. `git checkout MN-hotfix-logout-button`
4. `npm start`

### CODE REVIEW

**Review by mxmason — APPROVED** [review]
Looks like the bug is fixed! Thank you!

**Review by N-Zubko — APPROVED** [review]
It's working! phew!

**Comment by N-Zubko** [comment]
I saw this error message before in my PR too, but it would appear and then not reproduce when I was testing the changes. Now it is displayed in the console every time I log out.

`react_devtools_backend.js:4026 Warning: Cannot update a component (`BrowserRouter`) while rendering a different component (`App`). To locate the bad setState() call inside `App`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render`

**Review by mira-kine — APPROVED** [review]
Thank you for the quick fix!

**Comment by N-Zubko** [comment]
> I saw this error message before in my PR too, but it would appear and then not reproduce when I was testing the changes. Now it is displayed in the console every time I log out.
> 
> `react_devtools_backend.js:4026 Warning: Cannot update a component (`BrowserRouter`) while rendering a different component (`App`). To locate the bad setState() call inside `App`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render`

I will copy it here from Slack for history. @michellerenehey's solution to solve this bug: 

`useEffect(() => {
        if (confirmLogOut) {
            localStorage.clear();
            setListToken('');
            navigateTo('/');
            setConfirmLogOut(false);
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [confirmLogOut]);`

**Comment by michellerenehey** [comment]
> > I saw this error message before in my PR too, but it would appear and then not reproduce when I was testing the changes. Now it is displayed in the console every time I log out.
> > `react_devtools_backend.js:4026 Warning: Cannot update a component (`BrowserRouter`) while rendering a different component (`App`). To locate the bad setState() call inside `App`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render`
> 
> I will copy it here from Slack for history. @michellerenehey's solution to solve this bug:
> 
> ```
> useEffect(() => {
>         if (confirmLogOut) {
>             localStorage.clear();
>             setListToken('');
>             navigateTo('/');
>             setConfirmLogOut(false);
>         }
>         // eslint-disable-next-line react-hooks/exhaustive-deps
>     }, [confirmLogOut]);
> ```

Thank you, @N-Zubko!!

**Pull request merged**
